#
# tclpdf - PDF generation for Tcl
#
# afm - the 14 standard fonts (9.6.2.2)
#
# Copyright (C) 2026 Alexander Schoepe, Bochum, DE, <alx.tcl@sowaswie.de>
#
# See the file "license.terms" for information on usage and redistribution
# of this file (MIT License).
#
# The metrics themselves are in afmData.tcl, generated by tools/mkafm.tcl from
# the original Adobe AFM files. This module is the logic on top: resolving a
# family and style to a font name, measuring a string, and refusing to measure
# what cannot be written.
#
# IMPORTANT for PDF/A and therefore for ZUGFeRD: these fonts are NOT embedded.
# A document that uses them cannot be PDF/A conformant. They are here because
# they need no font file and are right for a quick layout - the moment a
# document has to be archived, an embedded TrueType face takes their place.
#

package require Tcl 8.6.11-
package require tclpdf::afmData 1.0-

namespace eval ::tclpdf::afm {
  namespace export {[a-z]*}
  namespace ensemble create

  # Family and style to font name. The names on the left are what a caller
  # writes; the ones on the right are what the PDF has to say.
  variable families {
    helvetica {{} Helvetica bold Helvetica-Bold italic Helvetica-Oblique
        bolditalic Helvetica-BoldOblique}
    arial {{} Helvetica bold Helvetica-Bold italic Helvetica-Oblique
        bolditalic Helvetica-BoldOblique}
    times {{} Times-Roman bold Times-Bold italic Times-Italic
        bolditalic Times-BoldItalic}
    courier {{} Courier bold Courier-Bold italic Courier-Oblique
        bolditalic Courier-BoldOblique}
    symbol {{} Symbol}
    zapfdingbats {{} ZapfDingbats}
  }

  # These two carry their own built-in encoding; WinAnsiEncoding must not be
  # declared for them and cp1252 says nothing about their character codes.
  variable symbolic {Symbol ZapfDingbats}
}

# The names of all 14 fonts.
proc ::tclpdf::afm::fonts {} {
  return [lsort [array names ::tclpdf::afmData::widths]]
}

# Turn a family and a style into a font name.
#
#   resolve helvetica bold      -> Helvetica-Bold
#   resolve Times-Italic        -> Times-Italic   (already a font name)
#   resolve times {bold italic} -> Times-BoldItalic
proc ::tclpdf::afm::resolve {family {style {}}} {
  variable families
  # An exact font name passes through - case-insensitively, so "helvetica-bold"
  # works as well as "Helvetica-Bold".
  #
  # Only when NO style was given, though. "helvetica" is both a family name and
  # a font name, so passing it through unconditionally silently dropped the
  # style: [resolve helvetica bold] returned Helvetica, and the heading came
  # out in the regular weight with nothing to indicate why.
  if {$style eq {}} {
    foreach name [fonts] {
      if {[string equal -nocase $name $family]} {
        return $name
      }
    }
  }
  set key [string tolower $family]
  if {![dict exists $families $key]} {
    return -code error "tclpdf: unknown font \"$family\" - known families are:\
        [join [lsort [dict keys $families]] {, }]"
  }
  # Normalise the style: a list, a string, any order, any case.
  set wanted {}
  foreach word [string tolower [join $style " "]] {
    foreach part [split $word " ,-"] {
      if {$part ne {}} {
        lappend wanted $part
      }
    }
  }
  set bold [expr {"bold" in $wanted}]
  set italic [expr {"italic" in $wanted || "oblique" in $wanted}]
  set styleKey ""
  if {$bold} {
    append styleKey bold
  }
  if {$italic} {
    append styleKey italic
  }
  set variants [dict get $families $key]
  if {![dict exists $variants $styleKey]} {
    return -code error "tclpdf: font family \"$family\" has no style\
        \"[join $style { }]\""
  }
  return [dict get $variants $styleKey]
}

proc ::tclpdf::afm::isSymbolic {font} {
  variable symbolic
  return [expr {$font in $symbolic}]
}

# The FontDescriptor values (9.8.1) of a font.
proc ::tclpdf::afm::descriptor {font} {
  Check $font
  return $::tclpdf::afmData::descriptor($font)
}

# The width of a single byte value, in 1/1000 em.
proc ::tclpdf::afm::width {font code} {
  Check $font
  return [lindex $::tclpdf::afmData::widths($font) $code]
}

# The width of a string at a given size, in points.
#
# The text is measured in the encoding it will be WRITTEN in - WinAnsi for the
# text fonts, the font's own for Symbol and ZapfDingbats. A character that
# cannot be written is an error, not a silently substituted question mark:
# this is the only place in the whole chain that notices a missing Euro sign.
# Neither veraPDF nor a PDF reader will.
proc ::tclpdf::afm::stringWidth {font text size} {
  Check $font
  set total 0
  foreach code [encode $font $text] {
    incr total [lindex $::tclpdf::afmData::widths($font) $code]
  }
  return [expr {$total * $size / 1000.0}]
}

# Encode text into the byte values this font uses, checking every character.
#
# Both the throw AND the round trip are needed, because the two interpreters
# fail differently - measured on U+4E2D:
#
#   Tcl 8.6.18  [encoding convertto cp1252] succeeds and yields "?", so only
#               comparing the round trip catches it.
#   Tcl 9.0.4   it throws by itself ("unexpected character at index 0"), which
#               is correct but says nothing about fonts or about what to do.
#
# Catching that and re-reporting it keeps the message identical under both,
# and the message is the point: this is the only place in the whole chain that
# notices a missing character. Neither veraPDF nor a PDF reader will.
proc ::tclpdf::afm::encode {font text} {
  Check $font
  return [encodeWidths $::tclpdf::afmData::widths($font) $text \
      [isSymbolic $font] "the standard font $font" \
      " - embed a TrueType font for this text"]
}

# The same against a width list handed in rather than looked up, so that an
# embedded single-byte face - a Type 1 program with its AFM - is encoded by
# this code and not by a second copy of it. The two differ in where the widths
# come from and in what the message may suggest; everything that can go wrong
# is the same.
proc ::tclpdf::afm::encodeWidths {widths text symbolic name {hint {}}} {
  set codes {}
  set position 0
  foreach char [split $text {}] {
    # A soft hyphen marks a place where a word MAY be broken; it is not a
    # character to set. Where the breaker used it, it has already put a real
    # hyphen there, and everywhere else it has to vanish - so it never reaches
    # a font. Written through as byte 0xAD it would not vanish: ISO 32000-1
    # Annex D.2 makes that code a second "hyphen" in WinAnsiEncoding, and a
    # reader would draw one at every offer. (Its neighbour 0xA0, the no-break
    # space, IS a character to set - Annex D.2 makes it a second "space",
    # and the width table carries the space width there for that reason.)
    # The zero width space U+200B likewise: a break opportunity, nothing to
    # set - and no WinAnsi position for it, so it would have been refused.
    if {$char eq "\u00AD" || $char eq "\u200B"} {
      incr position
      continue
    }
    if {$symbolic} {
      # No transcoding: the caller addresses the font's own encoding directly.
      set code [scan $char %c]
      if {$code > 255} {
        return -code error "tclpdf: character U+[format %04X $code] cannot be\
            written in $name, which has a 256-slot built-in encoding\
            (position $position)"
      }
    } else {
      if {[catch {encoding convertto cp1252 $char} byte]
          || [encoding convertfrom cp1252 $byte] ne $char} {
        return -code error "tclpdf: character U+[format %04X [scan $char %c]]\
            is not available in WinAnsiEncoding and cannot be written with\
            $name (position $position)$hint"
      }
      binary scan $byte cu code
    }
    if {[lindex $widths $code] == 0 && $code != 32} {
      return -code error "tclpdf: $name has no glyph for\
          U+[format %04X [scan $char %c]] (position $position)"
    }
    lappend codes $code
    incr position
  }
  return $codes
}

# The bytes a content stream needs for this text.
proc ::tclpdf::afm::bytes {font text} {
  return [binary format cu* [encode $font $text]]
}

proc ::tclpdf::afm::Check {font} {
  if {![info exists ::tclpdf::afmData::widths($font)]} {
    return -code error "tclpdf: \"$font\" is not one of the 14 standard fonts -\
        known are: [join [fonts] {, }]"
  }
  return
}

package provide tclpdf::afm 1.1
