#!/usr/bin/env tclsh
#
# tclpdf example 0.1 - the smallest complete program
#
#   tclsh examples/00.01-hello-world.tcl ?output.pdf?
#
# Ten lines write a valid PDF. Everything else in this directory is about what
# tclpdf can do; this one is about how little it takes to start.
#
# WHAT IS NOT HERE, because it does not have to be: no font call - the state
# starts at Helvetica 12 pt - no colour, no page size, no unit. The document
# defaults are A4 in millimetres at PDF 1.7. Say -format a4 anyway if it
# matters to the reader of the script; it is written out below for exactly
# that reason.
#
# The line the page carries ASKS for the two version numbers rather than
# stating them: [$doc cget -version] is what the file will be written as, and
# [package provide tclpdf] is the package doing the writing. A sentence typed
# out by hand would be right today and wrong after the next release, and
# nothing would notice - which is the habit this package keeps everywhere,
# down to the footer the other examples draw.
#
# The one line that is not about PDF at all is the auto_path: it makes the
# package findable while running from an unbuilt source tree - in FRONT of
# the path, so that the tree wins over an installed copy of the same version
# (Tcl runs the ifneeded script registered last, and reads auto_path from
# the back, so the first directory has the last word). After "make install"
# it is unnecessary - "package require tclpdf" finds it.
#
# Copyright (C) 2026 Alexander Schoepe, Bochum, DE
#
# See the file "license.terms" for information on usage and redistribution
# of this file (MIT License).

set auto_path [linsert $auto_path 0 [file dirname [file dirname [file normalize [info script]]]]]
package require tclpdf

set target [expr {[llength $argv] ? [lindex $argv 0] : "00.01-hello-world.pdf"}]

# A4 and millimetres are the defaults; they are named here so that the script
# says what it draws on. y counts from the TOP of the page, so {20 20} is
# 20 mm from the left edge and 20 mm below the top.
set doc [tclpdf new -format a4 -unit mm]
$doc page add
$doc text "Hello World - this is PDF [$doc cget -version] generated by\
    tclpdf [package provide tclpdf]." -at {20 20}
$doc write $target
$doc destroy

puts "  written: $target"
