#!/usr/bin/env tclsh
#
# tclpdf example 5.2 - a ZUGFeRD invoice, profile EN 16931
#
#   tclsh examples/05.02-zugferd-en16931.tcl ?output.pdf?
#
# A ZUGFeRD document is one invoice recorded twice: once for a person to read,
# once as XML for a machine. The construction is PDF/A-3 - everything embedded,
# colours anchored to a profile, metadata readable without decoding, and the
# XML attached with /AFRelationship /Alternative.
#
# EVERY FIGURE ON THIS PAGE IS READ OUT OF THE ATTACHED XML. That is not
# tidiness, it is the point: whoever opens the attachment must not find a
# second, different invoice. A document whose visible side disagrees with its
# own data is worse than one carrying no data at all - and no validator on the
# way to the recipient says a word about it.
#
# What tclpdf does here that is worth knowing:
#
#   The profile (MINIMUM, BASIC, EN 16931, EXTENDED) is read out of BT-24 of
#   the XML, not passed in. An unknown identifier is an ERROR - one widely
#   used generator silently substitutes BASIC instead, which is how an
#   EXTENDED invoice goes into circulation labelled wrongly.
#
#   /AF points straight at the file specification. The same generator puts a
#   second level of indirection in between; the file then passes PDF/A-3
#   validation while qpdf and poppler cannot find the invoice at all.
#
#   The XML is read and written as bytes. A line-ending conversion would be
#   invisible to every validator.
#
# The face is embedded because PDF/A requires it - the fourteen standard fonts
# are not embedded, so a document relying on them cannot be archived. That is
# the only reason; examples that do not need it do not do it.
#
# Checking the result, all three locally installed:
#
#   verapdf -f 3b out.pdf
#   qpdf --list-attachments out.pdf
#   pdftotext out.pdf -
#
#
# This example and 05.02 deliberately repeat each other. They exist to be read
# SIDE BY SIDE - same construction, different profile - and the repetition is
# what makes the one difference visible. Pulling the shared parts into a
# procedure would hide exactly what the pair is for, so the duplicate-scanner's
# finding on these two files is knowingly left standing.
#
# Copyright (C) 2026 Alexander Schoepe, Bochum, DE
#
# See the file "license.terms" for information on usage and redistribution
# of this file (MIT License).

set here [file dirname [file normalize [info script]]]
lappend auto_path [file dirname $here]
package require tclpdf

# The footer every example draws - shared, because one copy per example is
# how a block starts drifting.
source [file join $here common.tcl]

set target [expr {[llength $argv] ? [lindex $argv 0] : "05.02-zugferd-en16931.pdf"}]
set assets [file join $here assets]
set invoice [file join $assets xml zugferd-en16931.xml]

# Everything below is what the XML says. Kept in one place so that a mismatch
# is a change in one dictionary rather than a hunt through the layout.
set data {
    number       471113
    date         "20 February 2026"
    delivery     "3 June 2025"
    sellerName   "Lieferant GmbH"
    sellerStreet "Lieferantenstrasse 20"
    sellerCity   "80333 Muenchen"
    sellerTax    "201/113/40209"
    sellerVat    DE123456789
    buyerName    "Kunden AG Mitte"
    buyerStreet  "Kundenstrasse 15"
    buyerCity    "69876 Frankfurt"
    buyerRef     GE2020211
    itemNumber   SFK5
    itemName     "Schweinesteak"
    quantity     "4.0000"
    unit         kg
    unitPrice    "5.5000"
    lineTotal    "22.00"
    taxRate      "7.00"
    taxAmount    "1.54"
    netTotal     "22.00"
    grandTotal   "23.54"
    duePayable   "23.54"
}

set doc [tclpdf new -unit mm]
$doc info Title "Invoice [dict get $data number]"
$doc info Author [dict get $data sellerName]
$doc info Subject "ZUGFeRD invoice, profile EN 16931, generated by tclpdf"

$doc font embed body [file join $assets fonts DejaVuSans.ttf]
$doc font embed bodyBold [file join $assets fonts DejaVuSans-Bold.ttf]
$doc page add

# -- sender and recipient --------------------------------------------------

$doc font -family bodyBold -size 15
$doc text [dict get $data sellerName] -at {20 22}
$doc font -family body -size 8
$doc text "[dict get $data sellerStreet] - [dict get $data sellerCity]" -at {20 28}
$doc text "Tax number [dict get $data sellerTax] - VAT ID [dict get $data sellerVat]" \
    -at {20 32}

$doc font -size 9
$doc text [dict get $data buyerName] -at {20 50}
$doc text [dict get $data buyerStreet] -at {20 55}
$doc text [dict get $data buyerCity] -at {20 60}

# -- the invoice head ------------------------------------------------------

$doc font -family bodyBold -size 13
$doc text "Invoice [dict get $data number]" -at {20 78}
$doc font -family body -size 9
$doc text "Invoice date: [dict get $data date]" -at {20 86}
$doc text "Date of supply: [dict get $data delivery]" -at {20 91}
$doc text "Your reference: [dict get $data buyerRef]" -at {20 96}

# -- the one line item -----------------------------------------------------

set y [$doc table \
    -at {20 106} -width 170 -theme striped \
    -style {family body} -headStyle {family bodyBold} -footStyle {family bodyBold} \
    -head {{Pos Article Quantity Unit "Unit price" Amount}} \
    -body [list [list 1 \
        "[dict get $data itemName] ([dict get $data itemNumber])" \
        [dict get $data quantity] \
        [dict get $data unit] \
        [dict get $data unitPrice] \
        [dict get $data lineTotal]]] \
    -foot [list \
        [list [list text "Net total" colSpan 5 align right] [dict get $data netTotal]] \
        [list [list text "VAT [dict get $data taxRate] %" colSpan 5 align right] \
            [dict get $data taxAmount]] \
        [list [list text "Total due" colSpan 5 align right] [dict get $data grandTotal]]] \
    -columns {{width 12 align right} {} {width 24 align decimal} {width 14} \
        {width 26 align decimal} {width 26 align decimal}}]

# The quantity is 4.0000 and the unit price 5.5000 - four decimals, as the XML
# states them. The amounts have two. Decimal alignment is what keeps those in
# one column readable; right alignment would stagger the points.

$doc font -family body -size 9
$doc text "Payable without deduction. VAT category S at [dict get $data taxRate] %\
    on a basis of [dict get $data netTotal]." -at [list 20 [expr {$y + 10}]] -width 170

$doc font -size 8
$doc text "This document carries the same invoice as XML. Open the attachment\
    to compare - every figure above is taken from it. The file claims\
    PDF/A-3B - the level every invoice reaches without a structure tree,\
    declared by the one zugferd call regardless of the XML; the profile from\
    BT-24 decides the attachment's relationship, not the PDF/A level. A\
    document that wants 3U or 3A says so afterwards with pdfa -conformance." \
    -at [list 20 [expr {$y + 24}]] -width 170

$doc bookmark "Invoice [dict get $data number]" -page 0

# -- and the invoice a second time, for the machine ------------------------

# One call sets everything PDF/A-3B needs: the output intent with the sRGB
# profile the package ships, the XMP extension schema, the attachment with
# /AFRelationship /Alternative at document level, and the entry in the names
# tree. Passing -icc here would name the very file the module already finds -
# measured, the two documents come out identical.
#
# What decides the PDF/A level: nothing in the XML. [zugferd] always declares
# PDF/A-3B - the least the standards ask for and the level every invoice
# reaches without a structure tree; BT-24 gives the Factur-X profile
# (MINIMUM, BASIC WL, ...), which steers /AFRelationship and fx:ConformanceLevel,
# not the PDF/A conformance. A document that wants more says so afterwards:
# [$doc pdfa -conformance U] after this call raises the claim to 3U with the
# Factur-X extension in place, and A needs [tagged 1] besides - measured, the
# file then validates against the higher profile. -icc names another output
# intent profile (a CMYK one, see pdfa -profile); the colours are held against
# it at write time.
# The profile can be read before anything is attached: [zugferd profile]
# looks at BT-24 of the XML and answers with the Factur-X level, and refuses
# XML that carries no such identifier. Nothing is written by this call.
set channel [open $invoice rb]
set xml [read $channel]
close $channel
puts "  BT-24 read ahead: [$doc zugferd profile $xml]"

set profile [$doc zugferd $invoice]
puts "  profile from BT-24: $profile"
puts "  attachment: [dict get [$doc zugferd state] name],\
    [dict get [$doc zugferd state] bytes] bytes"

# -- the options, tried on documents that are thrown away ------------------

# The call above takes every default, and the defaults are right for this
# invoice. What the options do is shown below on documents of their own: a
# ZUGFeRD document carries exactly ONE invoice - a second call is refused -
# so each variant gets a fresh document in memory, is asked what it would
# write, and is destroyed unwritten. The file this example writes stays the
# one invoice above.
#
# The values are the ones the standards allow. -name is what a reader looks
# the attachment up by, and exactly four are permitted; -type goes verbatim
# into fx:DocumentType, ORDER being Order-X; -profile overrides BT-24 - meant
# for an XML whose identifier the reader does not know, and here it stands in
# for five different invoices, because one XML serves them all; -version is
# fx:Version, -description the attachment's text, -compress packs the XML
# with Flate (off by default: the invoice sits in the file byte for byte);
# -relationship overrides the /AFRelationship the profile prescribes - Data
# for MINIMUM and BASIC WL, Alternative for every fuller profile, Source where
# the XML is what the invoice was made from; XRECHNUNG is the sixth level, the
# one a reader answers for an XRechnung identifier; and -icc
# names another output intent profile in place of the shipped sRGB one -
# here the package's second sRGB profile, sRGB2014.
set srgb2014 [file join [file dirname $here] icc sRGB2014.icc]
set variants [list \
    {-name factur-x.xml -profile "EN 16931" -type INVOICE -version 1.0 \
        -description "EN 16931 invoice data" -compress 0} \
    {-name zugferd-invoice.xml -profile MINIMUM -relationship Data} \
    {-name xrechnung.xml -profile "BASIC WL"} \
    {-name xrechnung.xml -profile XRECHNUNG -relationship Source} \
    {-name order-x.xml -type ORDER -profile BASIC -description "Order-X order data"} \
    [list -profile EXTENDED -relationship Alternative -compress 1 -icc $srgb2014]]
puts "  the options, each on a throwaway document:"
foreach options $variants {
    set demo [tclpdf new]
    $demo zugferd $invoice {*}$options
    set state [$demo zugferd state]
    # The relationship is in the record - the one the profile prescribes, or
    # the one -relationship gave; the compression the attach module keeps.
    set attached [lindex [$demo state attachments] 0]
    puts [format "    %-20s %-9s %-7s /AFRelationship /%-11s intent %s%s" \
        [dict get $state name] [dict get $state profile] [dict get $state type] \
        [dict get $state relationship] \
        [file tail [dict get [$demo pdfa state] profile]] \
        [expr {[dict get $attached compress] ? ", Flate" : ""}]]
    $demo destroy
}

exampleFooter $doc

$doc write $target
puts "  written: $target ([file size $target] bytes)"
$doc destroy
