#!/usr/bin/env tclsh
#
# tclpdf example 5.13 - an Order-X purchase order, profile COMFORT
#
#   tclsh examples/05.13-order-x.tcl ?output.pdf?
#
# Order-X is the ordering side of the family that 05.01 and 05.02 show for
# invoices: the same hybrid construction - a page for a person, XML for a
# machine, PDF/A-3 around both - carrying an order instead of an invoice.
# The [zugferd] call handles it unchanged; what changes is the family:
#
#   Three levels of its own: BASIC, COMFORT, EXTENDED, read from BT-24
#   (urn:order-x.eu:1p0:basic|comfort|extended). Three document types:
#   ORDER, ORDER_RESPONSE, ORDER_CHANGE - an order XML becomes an ORDER
#   unless -type names one of the other two. ONE file name, order-x.xml.
#   /AFRelationship /Data by default; Source and Alternative are the two
#   other values the standard permits. And the extension schema goes under
#   the Order-X namespace URI, without the ":invoice" of Factur-X.
#
#   The families are bound: a conformance level, type or file name of the
#   invoice family is refused for an order and the other way round, naming
#   both sides. A Factur-X BASIC invoice cannot go out labelled an Order-X
#   BASIC order just because the level shares a word.
#
# A document carries exactly ONE order, so ORDER_RESPONSE, ORDER_CHANGE and
# the -profile override are shown the way 05.02 shows its options: each on a
# fresh document in memory that is asked what it would write and destroyed
# unwritten. The file this example writes stays the one purchase order.
#
# THE XML HERE IS A HULL, NOT A FULL ORDER MESSAGE. It carries the message
# root and BT-24 - everything [zugferd] reads - and is built by this script
# the same way the test suite builds it. A real deployment attaches the
# complete SCRDM order message its ERP produced; composing that message is
# the ERP's job, not this package's. That is also why, unlike 05.01/05.02,
# the figures on this page are illustrative rather than read out of the
# attachment - the hull has no figures to read.
#
# Check with:  verapdf -f 3b out.pdf  and  qpdf --list-attachments out.pdf
#
# Copyright (C) 2026 Alexander Schoepe, Bochum, DE
#
# See the file "license.terms" for information on usage and redistribution
# of this file (MIT License).

set here [file dirname [file normalize [info script]]]
lappend auto_path [file dirname $here]
package require tclpdf

# The footer every example draws - shared, because one copy per example is
# how a block starts drifting.
source [file join $here common.tcl]

set target [expr {[llength $argv] ? [lindex $argv 0] : "05.13-order-x.pdf"}]
set outdir [file dirname [file normalize $target]]

# The Order-X hull: message root and BT-24, all the module reads. Written
# next to the output file - never into the source tree - and deleted at the
# end. The file is deliberately NOT called order-x.xml: without -name an
# order is embedded as order-x.xml - the one name the standard allows -
# whatever the file on disk is called.
set orderXmlFiles {}
proc orderXml {name identifier} {
    set path [file join $::outdir $name]
    lappend ::orderXmlFiles $path
    set f [open $path wb]
    puts -nonewline $f [string map [list @ID@ $identifier] {<rsm:SCRDMCCBDACIOMessageStructure xmlns:rsm="urn:un:unece:uncefact:data:SCRDMCCBDACIOMessageStructure:100" xmlns:ram="urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:128">
  <rsm:ExchangedDocumentContext>
    <ram:GuidelineSpecifiedDocumentContextParameter>
      <ram:ID>@ID@</ram:ID>
    </ram:GuidelineSpecifiedDocumentContextParameter>
  </rsm:ExchangedDocumentContext>
</rsm:SCRDMCCBDACIOMessageStructure>
}]
    close $f
    return $path
}

set order [orderXml 05.13-order-comfort.xml urn:order-x.eu:1p0:comfort]

# What the page shows. In an order the customer is the issuer and the
# supplier the recipient - the same cast as 05.02, with the roles reversed.
set data {
    number       87421
    date         "18 August 2026"
    delivery     "1 September 2026"
    buyerName    "Kunden AG Mitte"
    buyerStreet  "Kundenstrasse 15"
    buyerCity    "69876 Frankfurt"
    sellerName   "Lieferant GmbH"
    sellerStreet "Lieferantenstrasse 20"
    sellerCity   "80333 Muenchen"
    netTotal     "42.80"
}

set doc [tclpdf new -unit mm]
$doc info Title "Purchase order [dict get $data number]"
$doc info Author [dict get $data buyerName]
$doc info Subject "Order-X purchase order, profile COMFORT, generated by tclpdf"

# PDF/A requires every font embedded; the fourteen standard faces are not.
$doc font embed body [file join $here assets fonts DejaVuSans.ttf]
$doc font embed bodyBold [file join $here assets fonts DejaVuSans-Bold.ttf]
$doc page add

# -- who orders from whom --------------------------------------------------

$doc font -family bodyBold -size 15
$doc text [dict get $data buyerName] -at {20 22}
$doc font -family body -size 8
$doc text "[dict get $data buyerStreet] - [dict get $data buyerCity]" -at {20 28}

$doc font -size 9
$doc text [dict get $data sellerName] -at {20 46}
$doc text [dict get $data sellerStreet] -at {20 51}
$doc text [dict get $data sellerCity] -at {20 56}

# -- the order head --------------------------------------------------------

$doc font -family bodyBold -size 13
$doc text "Purchase order [dict get $data number]" -at {20 74}
$doc font -family body -size 9
$doc text "Order date: [dict get $data date]" -at {20 82}
$doc text "Requested delivery: [dict get $data delivery]" -at {20 87}

# -- the order lines -------------------------------------------------------

# Quantities and unit prices with four decimals, amounts with two - the way
# EN 16931 and Order-X state them. Decimal alignment keeps each column
# readable; right alignment would stagger the points.
set y [$doc table \
    -at {20 97} -width 170 -theme striped \
    -style {family body} -headStyle {family bodyBold} -footStyle {family bodyBold} \
    -head {{Pos Article Quantity Unit "Unit price" Amount}} \
    -body {
        {1 "Schweinesteak (SFK5)" 4.0000 kg 5.5000 22.00}
        {2 "Mineralwasser 0.75 l (GTRWR5)" 20.0000 btl 0.7900 15.80}
        {3 "Transportkiste (KT12)" 2.0000 pcs 2.5000 5.00}} \
    -foot [list \
        [list [list text "Net total" colSpan 5 align right] [dict get $data netTotal]]] \
    -columns {{width 12 align right} {} {width 24 align decimal} {width 14} \
        {width 26 align decimal} {width 26 align decimal}}]

$doc font -family body -size 9
$doc text "Prices are net as quoted; VAT is applied at invoicing." \
    -at [list 20 [expr {$y + 10}]] -width 170

$doc font -size 8
$doc text "This document carries the order as XML in the attachment\
    order-x.xml - the one file name Order-X allows - with /AFRelationship\
    /Data, the default for an order. The conformance level COMFORT is read\
    out of BT-24 of the XML, not passed in, and the file claims PDF/A-3B,\
    declared by the one zugferd call. Levels, types and names are bound to\
    their family: an invoice level on an order is refused naming both, so a\
    document cannot leave labelled as something its data is not." \
    -at [list 20 [expr {$y + 24}]] -width 170

$doc bookmark "Purchase order [dict get $data number]" -page 0

# -- and the order for the machine -----------------------------------------

# The level can be read before anything is attached: [zugferd profile] looks
# at BT-24 and answers COMFORT for urn:order-x.eu:1p0:comfort. Nothing is
# written by this call.
set channel [open $order rb]
set xml [read $channel]
close $channel
puts "  BT-24 read ahead: [$doc zugferd profile $xml]"

# One call sets everything PDF/A-3B needs, exactly as for an invoice: the
# output intent with the shipped sRGB profile, the XMP extension schema -
# under the Order-X namespace URI, without the ":invoice" of Factur-X - the
# attachment at document level, and the entry in the names tree. What the
# family changes: the document becomes an ORDER, the attachment is named
# order-x.xml, and /AFRelationship is /Data - the Order-X default, where a
# full-profile invoice gets /Alternative.
set profile [$doc zugferd $order]
puts "  profile from BT-24: $profile"
puts "  attachment: [dict get [$doc zugferd state] name],\
    [dict get [$doc zugferd state] bytes] bytes,\
    type [dict get [$doc zugferd state] type],\
    /AFRelationship /[dict get [$doc zugferd state] relationship]"

# -- the other types and the override, on throwaway documents --------------

# A document carries exactly ONE order - a second call is refused - so each
# variant gets a fresh document in memory, is asked what it would write, and
# is destroyed unwritten.
#
#   -type ORDER_RESPONSE   the seller answering the order; a response has to
#                          be named, BT-24 alone always means ORDER
#   -type ORDER_CHANGE     the buyer changing an order already placed
#   -profile COMFORT       overrides the level read from BT-24 - meant for
#                          an XML whose identifier the reader does not know;
#                          the FAMILY still comes from BT-24, so the order
#                          stays an ORDER and does not fall back to INVOICE
set basic [orderXml 05.13-order-basic.xml urn:order-x.eu:1p0:basic]
puts "  the order types and the override, each on a throwaway document:"
foreach options {
    {-type ORDER_RESPONSE}
    {-type ORDER_CHANGE}
    {-profile COMFORT}
} {
    set demo [tclpdf new]
    $demo zugferd $basic {*}$options
    set state [$demo zugferd state]
    puts [format "    %-22s %-9s %-14s /AFRelationship /%s" \
        [dict get $state name] [dict get $state profile] \
        [dict get $state type] [dict get $state relationship]]
    $demo destroy
}

# The family binding, shown live: EN 16931 is an invoice level, this XML is
# an order, and the refusal names both sides. A refused zugferd leaves no
# PDF/A claim, no schema and no attachment behind.
set demo [tclpdf new]
catch {$demo zugferd $basic -profile "EN 16931"} refusal
puts "  refused across families:"
puts "    $refusal"
$demo destroy

exampleFooter $doc

$doc write $target
puts "  written: $target ([file size $target] bytes)"
puts "  [exampleArchival $doc]"
$doc destroy

# The hulls served their purpose; only the PDF remains.
foreach path $orderXmlFiles {
    file delete $path
}
